### ISSUE TITLE
Cookie not set !

### ISSUE THREAD

**Issue by danielb2** [coder-alpha/FMoviesPlus.bundle#15] opened 2017-07-17 23:21 UTC
I'm getting a cookie not set error in both the chrome app and regular browser mode.

Steps to reproduce:

Navigate to: Channels > FMoviesPlus > Movies & TV-Series > Movies

After clicking Movies I get this error. same with selecting TV-Series. Clicking "Most watched"  gives me just an empty page.

![screen shot 2017-07-17 at 4 16 58 pm](https://user-images.githubusercontent.com/26678/28293938-bb80233c-6b0b-11e7-873c-200998e96f8a.png)

Plex server: Version 1.7.5.4035

any ideas?

**Comment by coder-alpha** [comment] 2017-07-18 01:11
Did you restart PMS after update or is this a new install ? Please restart your PMS if updated from previous version.

Let me know if that fixes the issue.

**Comment by danielb2** [comment] 2017-07-18 04:43
This was a fresh install. I've never used FMoviesPlus  before. I had restarted PMS after the install to get it to load

**Comment by coder-alpha** [comment] 2017-07-18 05:34
Whats your OS ? If its non Windows can you enable the option Alternate SSL under the channel settings/prefs. and try again ? 
Also, PlexWeb interface can cache pages sometimes, so clear cache using the plugin > options > clear cache and also on the browser and then try.

If issue persists can u provide your channel log. More info to access the channel log is in the first post on the Plex forum thread https://forums.plex.tv/discussion/255348/p1

**Comment by danielb2** [comment] 2017-07-18 18:29
I changed the alternative SSL, and then I get a message saying `This channel is not responding`.

I couldn't find plugin > options > clear cache.  Where do I find `plugin` ?

**Comment by coder-alpha** [comment] 2017-07-18 20:16
> I changed the alternative SSL, and then I get a message saying This channel is not responding.

Seems something is either not initialized or not working properly. Which OS is your PMS installed on and which client are u using ? I'll probably need the logs to troubleshoot the issue.

I meant from the channel plugin's menu navigate to Options > Clear Cache.

**Comment by danielb2** [comment] 2017-07-18 21:49
OS: FreeBSD  11.0-RELEASE-p1

How can I provide logs?

Sorry, I can't seem to find the channel plugin's menu. I'm blind as a bat. I can find "Channels" and the plugin. But I don't see any Options with clear cache anywhere.  I've checked both plex settings and the settings for this plugin.

**Comment by coder-alpha** [comment] 2017-07-18 22:04
> How can I provide logs?

Info to access the channel log is in the first post on the Plex forum thread https://forums.plex.tv/discussion/255348/p1

> Sorry, I can't seem to find the channel plugin's menu. I'm blind as a bat. I can find "Channels" and the plugin. But I don't see any Options with clear cache anywhere. I've checked both plex settings and the settings for this plugin.

Sorry maybe my directions were not clear.
![image](https://user-images.githubusercontent.com/10291660/28341790-1ee89620-6be3-11e7-90e0-bdfc98da2bdf.png)

**Comment by coder-alpha** [comment] 2017-07-19 03:42
Ok, I ended up installing FreeBSD on my VM and can replicate the 'Cookie not set' error. Give me a day or so while I look into this.. You can use the External Listing menu in the mean time to access using other sources.

**Comment by coder-alpha** [comment] 2017-07-20 02:56
I will push out an update tomorrow but this is a cache issue. You should be able to resolve it once you have the 'Alternate SSL' option enabled and run the clear cache option and also clear the cache from your browser. Then run the Reset Cookie option.

There is a cached copy of the webpage that was downloaded before the Alternate SSL got enabled that's causing this issue.

**Comment by danielb2** [comment] 2017-07-20 03:29
awesome. that was very quick :)

**Comment by coder-alpha** [comment] 2017-07-21 23:08
I'm assuming that resolved your issue, so closing this issue. Feel free to open in case issue persists. I did also put out an update v.0.39 to address that issue https://github.com/coder-alpha/FMoviesPlus.bundle/releases/tag/v0.39

**Comment by danielb2** [comment] 2017-07-22 18:25
finally got a chance to look. I updated via webtools USA.  restarted plex. cleared cache. made sure Alternate SSL is checked. Now I got "channel not responding" 😢

**Comment by coder-alpha** [comment] 2017-07-22 18:33
did u perform Reset Cookie ?

clear browser cache. or try with a different browser.

Logs would be helpful otherwise.

**Comment by ag0380** [comment] 2017-07-23 04:51
I am using windows 10 and installed this plugin for first time a couple of days back. Have been having this cookie problem in both 38 and 39 versions
[logs.zip](https://github.com/coder-alpha/FMoviesPlus.bundle/files/1167861/logs.zip)

**Comment by coder-alpha** [comment] 2017-07-24 01:57
@ag0380 
Can you access the site https://fmovies.to from your PMS machine's browser ?
Please enable debug mode from settings/prefs.

Then Clear Cache (under Options), Clear browser cache, Reset Cookies (under Options). And try again.

If this does not still work, I would recommend using WebTools to perform an Uninstall and then Reinstall.

**Comment by jnickz** [comment] 2017-07-28 07:27
I have got the same problem, after freshly install Plex, i go on and add webtools plugin. 
Then add the fmovies plugin, and always get "This channel is not responding."
Can not seems to load any thing from it.

**Comment by coder-alpha** [comment] 2017-07-28 08:31
@jnickz 
Which OS, PMS ver. ? Did you try a PMS restart ?
Can you access the main menu of the channel ? Or do you only get "This channel is not responding." message. PlexWeb has cache issues, so please clear your browser cache after you have tried Clear Cache and Reset Cookies.

Ver. 0.40 requires Node.js or hook.io setup 
https://forums.plex.tv/discussion/255348/rel-fmoviesplus-channel/p1#methods

Logs would be helpful otherwise.

**Comment by jnickz** [comment] 2017-07-28 15:53
I am using on Macbook pro.
I found out that when i visit plex.tv , the movies does loads, but no on my local host, however i am unable to play any video at all. 
Not sure what is going on, will have to do do a little bit of troubleshooting here.

**Comment by coder-alpha** [comment] 2017-07-28 17:04
@jnickz 
Probably your PMS ver. is old. The plex.tv interface of PlexWeb has the latest interface, the one you use via localhost is the one that is bundled with PMS.
Do make sure to enable setting Alternate SSL.

**Comment by jnickz** [comment] 2017-07-29 02:20
The PMS i am using is Version 1.7.5, it was freshly download from plex.tv website and installed to my macbookpro.
I found a solution to my problem:
1st remove all devices
2nd make sure to sign out both local and plex.tv
3rd clear cache/browser cookie
4th relogin, and both online and local is working again.
There seems to be a problem, which i dont know why.

**Comment by coder-alpha** [comment] 2017-07-29 19:30
hmm.. that's an odd solution but well good if it works for you.

I still feel this is related to a cached copy being used and not the new copy of the file being retrieved.

So,...
1. Clear Cache (Under Channel's option menu)
2. Reset Cookies (Under Channel's option menu)
3. Clear browser cache (or using Chrome open the Inspect tool > Network tab > Disable cache and browse with the Inspect tool open - enforces no cache)

...should fix it.

**Closed** 2017-08-14 19:51 UTC

**Comment by privatadata** [comment] 2018-09-04 17:34
I cannot get this plugin to work even though this is a new install of FMoviesPlus.bundle-0.73 using the instructions provided (and I have never installed this plugin previously). I even cleared my browser history, cache and cookies.

I don't understand what the problem is, although the outcome is the same as is being reported by other users.

PLEASE HELP

**Comment by coder-alpha** [comment] 2018-09-04 19:11
@privatadata You might want to create a new issue. Also, will need more info regarding your system and your settings for FMoviesPlus plugin. Log files with Debug enabled under settings would help.
